version: '3.8'

networks:
  nest-net:
    name: nest-net

services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./package.json:/home/node/nest-test/package.json
      - ./.env:/home/node/nest-test/.env
      - ./node_modules:/home/node/nest-test/node_modules
      - ./src:/home/node/nest-test/src
      - ./tests:/home/node/nest-test/tests
    environment:
      - NODE_ENV=development
    working_dir: /home/node/nest-test
    container_name: nest-back
    networks:
      - nest-net
    ports:
      - 3000:3000
    tty: true

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network
